export const RESULTS = [
  // 2026
  {
    id: "2026-wsk-sms-lonato-final",
    date: "2026-03-02",
    year: 2026,
    championship: "WSK Super Master Series",
    circuit: "Lonato",
    city: "Lonato del Garda",
    country: "IT",
    category: "OK",
    position: 1,
    resultType: "win" as const,
    notes: "Won the OK Final at Lonato — WSK Super Master Series",
    featured: true,
  },
  {
    id: "2026-wsk-sms-overall",
    date: "2026-04-06",
    year: 2026,
    championship: "WSK Super Master Series",
    circuit: "Multiple circuits",
    city: "Italy",
    country: "IT",
    category: "OK",
    position: 3,
    resultType: "podium" as const,
    notes: "3rd in overall OK championship (308 pts) — WSK Super Master Series",
    featured: true,
  },
  {
    id: "2026-cotf-mulsen",
    date: "2026-06-06",
    year: 2026,
    championship: "Champions of the Future",
    circuit: "Motorsport Arena Mülsen",
    city: "Mülsen",
    country: "DE",
    category: "OK",
    position: 2,
    resultType: "podium" as const,
    notes: "P2 at Champions of the Future — Mülsen",
    featured: true,
  },
  {
    id: "2026-cotf-valencia",
    date: "2026-04-05",
    year: 2026,
    championship: "Champions of the Future",
    circuit: "Circuito Int. Lucas Guerrero",
    city: "Valencia",
    country: "ES",
    category: "OK",
    position: 4,
    resultType: "finish" as const,
    notes: "P4 at Champions of the Future — Valencia",
    featured: false,
  },
  {
    id: "2026-wsk-euro-viterbo",
    date: "2026-05-11",
    year: 2026,
    championship: "WSK Euro Series",
    circuit: "Viterbo",
    city: "Viterbo",
    country: "IT",
    category: "OK",
    position: 2,
    resultType: "podium" as const,
    notes: "P2 at the Viterbo round",
    featured: true,
  },
  {
    id: "2026-fia-euro-la-conca",
    date: "2026-06-08",
    year: 2026,
    championship: "FIA Karting European Championship — OK",
    circuit: "La Conca",
    city: "Muro Leccese",
    country: "IT",
    category: "OK",
    position: 5,
    resultType: "finish" as const,
    notes: "P5 after qualifying heats — running inside top 5",
    featured: false,
  },
  // 2025
  {
    id: "2025-fia-world-sweden",
    date: "2025-09-28",
    year: 2025,
    championship: "FIA Karting World Championship — OK-Junior",
    circuit: "Åsum Ring",
    city: "Kristianstad",
    country: "SE",
    category: "OK-Junior",
    position: 12,
    resultType: "finish" as const,
    notes: "Qualified 5th for the OK-Junior World Final, finished 12th",
    featured: true,
  },
  // 2024
  {
    id: "2024-iame-winter-cup",
    date: "2024-02-25",
    year: 2024,
    championship: "IAME Winter Cup",
    circuit: "La Conca",
    city: "Muro Leccese",
    country: "IT",
    category: "Mini/Cadet",
    position: 1,
    resultType: "win" as const,
    notes: "IAME Winter Cup Champion",
    featured: true,
  },
  {
    id: "2024-iame-euro-r1-zuera",
    date: "2024-04-14",
    year: 2024,
    championship: "IAME Euro Series",
    circuit: "Zuera",
    city: "Zuera",
    country: "ES",
    category: "Mini/Cadet",
    position: 1,
    resultType: "win" as const,
    notes: "Won Round 1 at Zuera",
    featured: true,
  },
  {
    id: "2024-iame-finals-pole",
    date: "2024-10-23",
    year: 2024,
    championship: "IAME International Finals",
    circuit: "Le Mans",
    city: "Le Mans",
    country: "FR",
    category: "Mini/Cadet",
    position: 1,
    resultType: "win" as const,
    notes: "Pole position — IAME International Finals",
    featured: true,
  },
  {
    id: "2024-iame-euro-genk",
    date: "2024-06-09",
    year: 2024,
    championship: "IAME Euro Series",
    circuit: "Genk",
    city: "Genk",
    country: "BE",
    category: "Mini/Cadet",
    position: 6,
    resultType: "finish" as const,
    notes: "P6 Genk",
    featured: false,
  },
  {
    id: "2024-iame-euro-franciacorta",
    date: "2024-07-21",
    year: 2024,
    championship: "IAME Euro Series",
    circuit: "Franciacorta",
    city: "Franciacorta",
    country: "IT",
    category: "Mini/Cadet",
    position: 9,
    resultType: "finish" as const,
    notes: "P9 Franciacorta",
    featured: false,
  },
  {
    id: "2024-fia-2nd-ranking",
    date: "2024-12-31",
    year: 2024,
    championship: "FIA Ranking",
    circuit: "Season overall",
    city: "Europe",
    country: "EU",
    category: "Mini/Cadet",
    position: 2,
    resultType: "podium" as const,
    notes: "2nd in FIA 2024 ranking; Europe 5th overall",
    featured: true,
  },
  // 2023
  {
    id: "2023-iame-euro-mariembourg",
    date: "2023-08-06",
    year: 2023,
    championship: "IAME Euro Series",
    circuit: "Mariembourg",
    city: "Mariembourg",
    country: "BE",
    category: "Mini/Cadet",
    position: 3,
    resultType: "podium" as const,
    notes: "P3 in Mariembourg",
    featured: false,
  },
  {
    id: "2023-iame-euro-zuera-heats",
    date: "2023-05-14",
    year: 2023,
    championship: "IAME Euro Series",
    circuit: "Zuera",
    city: "Zuera",
    country: "ES",
    category: "Mini/Cadet",
    position: 1,
    resultType: "win" as const,
    notes: "Heat wins — 1st, 2nd, 4th in heats",
    featured: false,
  },
  {
    id: "2023-national-campillos",
    date: "2023-09-17",
    year: 2023,
    championship: "National Championship",
    circuit: "Campillos",
    city: "Campillos",
    country: "ES",
    category: "Mini/Cadet",
    position: 3,
    resultType: "podium" as const,
    notes: "P3 Campillos National",
    featured: false,
  },
  {
    id: "2023-valencian-cup",
    date: "2023-10-29",
    year: 2023,
    championship: "Valencian Cup",
    circuit: "Chiva",
    city: "Chiva",
    country: "ES",
    category: "Mini/Cadet",
    position: 2,
    resultType: "podium" as const,
    notes: "P2 and P3 in the Valencian Cup",
    featured: false,
  },
  {
    id: "2023-euro-4th-overall",
    date: "2023-12-31",
    year: 2023,
    championship: "IAME Euro Series",
    circuit: "Season overall",
    city: "Europe",
    country: "EU",
    category: "Mini/Cadet",
    position: 4,
    resultType: "finish" as const,
    notes: "4th in European general classification",
    featured: true,
  },
  // 2022
  {
    id: "2022-national-zuera-r1",
    date: "2022-05-01",
    year: 2022,
    championship: "National Championship",
    circuit: "Zuera",
    city: "Zuera",
    country: "ES",
    category: "Cadet",
    position: 1,
    resultType: "win" as const,
    notes: "Double win — 1st and 1st at Zuera National",
    featured: false,
  },
  {
    id: "2022-cck-chiva",
    date: "2022-06-12",
    year: 2022,
    championship: "CCK",
    circuit: "Chiva",
    city: "Chiva",
    country: "ES",
    category: "Cadet",
    position: 2,
    resultType: "podium" as const,
    notes: "P2 and P3 at CCK Chiva",
    featured: false,
  },
  {
    id: "2022-national-campillos",
    date: "2022-09-11",
    year: 2022,
    championship: "National Championship",
    circuit: "Campillos",
    city: "Campillos",
    country: "ES",
    category: "Cadet",
    position: 2,
    resultType: "podium" as const,
    notes: "P2 and P3 at Campillos National",
    featured: false,
  },
  {
    id: "2022-leconte-chiva",
    date: "2022-07-24",
    year: 2022,
    championship: "Le Conte Cup",
    circuit: "Chiva",
    city: "Chiva",
    country: "ES",
    category: "Cadet",
    position: 1,
    resultType: "win" as const,
    notes: "P1 and P2 at Le Conte Chiva",
    featured: false,
  },
  {
    id: "2022-spanish-championship-3rd",
    date: "2022-12-31",
    year: 2022,
    championship: "Spanish Championship",
    circuit: "Season overall",
    city: "Spain",
    country: "ES",
    category: "Cadet",
    position: 3,
    resultType: "podium" as const,
    notes: "3rd overall in the Spanish Championship",
    featured: true,
  },
];

export const CALENDAR_EVENTS = [
  {
    id: "2026-wsk-sms",
    title: "WSK Super Master Series",
    startDate: "2026-02-20",
    endDate: "2026-04-06",
    circuit: "Multiple (Lonato, Adria, etc.)",
    city: "Italy",
    country: "IT",
    championship: "WSK Super Master Series",
    round: "Season",
    status: "completed" as const,
  },
  {
    id: "2026-cotf-valencia",
    title: "Champions of the Future",
    startDate: "2026-04-02",
    endDate: "2026-04-05",
    circuit: "Circuito Int. Lucas Guerrero",
    city: "Valencia",
    country: "ES",
    championship: "Champions of the Future",
    round: "Round",
    status: "completed" as const,
  },
  {
    id: "2026-wsk-euro",
    title: "WSK Euro Series",
    startDate: "2026-04-25",
    endDate: "2026-05-25",
    circuit: "Viterbo / Castelletto",
    city: "Italy",
    country: "IT",
    championship: "WSK Euro Series",
    round: "Season",
    status: "completed" as const,
  },
  {
    id: "2026-fia-euro-r1",
    title: "FIA Karting European Championship — OK",
    startDate: "2026-04-09",
    endDate: "2026-04-12",
    circuit: "World Circuit La Conca",
    city: "Muro Leccese",
    country: "IT",
    championship: "FIA Karting European Championship — OK",
    round: "Round 1",
    status: "completed" as const,
  },
  {
    id: "2026-fia-euro-r2",
    title: "FIA Karting European Championship — OK",
    startDate: "2026-05-07",
    endDate: "2026-05-10",
    circuit: "Circuito Int. Lucas Guerrero",
    city: "Chiva, Valencia",
    country: "ES",
    championship: "FIA Karting European Championship — OK",
    round: "Round 2",
    status: "completed" as const,
  },
  {
    id: "2026-cotf-mulsen",
    title: "Champions of the Future",
    startDate: "2026-06-03",
    endDate: "2026-06-06",
    circuit: "Motorsport Arena Mülsen",
    city: "Mülsen",
    country: "DE",
    championship: "Champions of the Future",
    round: "Round",
    status: "completed" as const,
  },
  {
    id: "2026-fia-euro-r3",
    title: "FIA Karting European Championship — OK",
    startDate: "2026-06-11",
    endDate: "2026-06-14",
    circuit: "Motorsport Arena Mülsen",
    city: "Mülsen",
    country: "DE",
    championship: "FIA Karting European Championship — OK",
    round: "Round 3",
    status: "completed" as const,
  },
  {
    id: "2026-fia-euro-r4",
    title: "FIA Karting European Championship — OK",
    startDate: "2026-07-30",
    endDate: "2026-08-02",
    circuit: "Åsum Ring",
    city: "Kristianstad",
    country: "SE",
    championship: "FIA Karting European Championship — OK",
    round: "Round 4",
    status: "upcoming" as const,
  },
  {
    id: "2026-cotf-kristianstad",
    title: "Champions of the Future",
    startDate: "2026-07-29",
    endDate: "2026-08-01",
    circuit: "Åsum Ring",
    city: "Kristianstad",
    country: "SE",
    championship: "Champions of the Future",
    round: "Round",
    status: "upcoming" as const,
  },
  {
    id: "2026-cotf-sarno",
    title: "Champions of the Future",
    startDate: "2026-09-10",
    endDate: "2026-09-13",
    circuit: "Circuito Internazionale di Sarno",
    city: "Sarno",
    country: "IT",
    championship: "Champions of the Future",
    round: "Round",
    status: "upcoming" as const,
  },
  {
    id: "2026-fia-world",
    title: "FIA Karting World Championship — OK",
    startDate: "2026-09-24",
    endDate: "2026-09-27",
    circuit: "To be confirmed",
    city: "To be confirmed",
    country: "EU",
    championship: "FIA Karting World Championship — OK",
    round: "Final",
    status: "upcoming" as const,
  },
];

export const SPONSORS = [
  {
    id: "swissquote",
    name: "Swissquote",
    tier: "title" as const,
    url: "https://www.swissquote.com",
    active: true,
  },
];

export const PARTNER_TIERS = [
  {
    id: "title",
    name: "Title Partner",
    blurb: "Maximum visibility. Your brand on the helmet, suit, and kart — the images that travel the world.",
    benefits: [
      "Full naming rights",
      "Helmet livery",
      "Race suit branding",
      "Kart main panel",
      "All social media content",
      "Press release mentions",
      "VIP hospitality at 2 events",
      "Official website header",
    ],
  },
  {
    id: "primary",
    name: "Primary Partner",
    blurb: "Prominent placement across all visual assets and social channels.",
    benefits: [
      "Kart side pod branding",
      "Race suit logo",
      "Social media posts (monthly)",
      "Website partner section",
      "1 event hospitality",
    ],
  },
  {
    id: "technical",
    name: "Technical Partner",
    blurb: "Product or service in exchange for category-exclusive technical partnership rights.",
    benefits: [
      "Category exclusivity",
      "Kart rear wing logo",
      "Website listing",
      "Social mention",
    ],
  },
  {
    id: "supporter",
    name: "Supporter",
    blurb: "Brand association with a rising European motorsport talent.",
    benefits: [
      "Website logo",
      "Social mention (bi-annual)",
      "Sticker pack",
    ],
  },
];

export const ACHIEVEMENTS = [
  {
    id: "wsk-final-win",
    title: "WSK Super Master Series — Final Winner",
    year: 2026,
    description: "Won the OK Final at Lonato — WSK Super Master Series",
    icon: "trophy",
  },
  {
    id: "wsk-p3-overall",
    title: "WSK Super Master Series — P3 Overall",
    year: 2026,
    description: "3rd in the overall championship (308 pts) in the toughest OK field of the season",
    icon: "podium",
  },
  {
    id: "iame-winter-cup",
    title: "IAME Winter Cup Champion",
    year: 2024,
    description: "International IAME Winter Cup — Champion",
    icon: "trophy",
  },
  {
    id: "fia-worlds-2025",
    title: "FIA World Championship — 12th in the World",
    year: 2025,
    description: "Qualified 5th for the FIA Karting World Championship OK-Junior Final in Sweden, finished 12th",
    icon: "globe",
  },
  {
    id: "iame-euro-r1-zuera",
    title: "IAME Euro Series Round 1 — Winner",
    year: 2024,
    description: "Won Round 1 of the IAME Euro Series at Zuera, Spain",
    icon: "trophy",
  },
  {
    id: "iame-finals-pole",
    title: "IAME International Finals — Pole Position",
    year: 2024,
    description: "Pole position at the IAME International Finals",
    icon: "trophy",
  },
];
